# File is explained in .\customer-service\src\main\resources\application.yaml, for educational purposes.
server:
  port: 8081
  servlet:
    context-path: /casa # category service api

spring:
  application:
    name: category-service
  datasource:
    username: category_user
    password: 123
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://category-db:5432/category_service_db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
